# Generated by Django 5.0 on 2023-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provincia', models.CharField(max_length=30)),
                ("dependencia_Id", models.CharField(max_length=30)),
                ('Nombre_distrito', models.CharField(max_length=30)),
                ('Numero_distrito', models.CharField(max_length=30)),
                ('Codigo_circuito', models.CharField(max_length=30)),
                ('Nombre_circuito', models.CharField(max_length=30)),
                ('Numero_subcircuito', models.CharField(max_length=30)),
                ('Codigo_subcircuito', models.CharField(max_length=30)),
                ('Nombre_subcircuito', models.CharField(max_length=30)),
            ],
        ),
    ]
