# Generated by Django 5.0 on 2023-12-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0002_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcircuito', models.CharField(max_length=30)),
                ('Codigo_subcircuito', models.CharField(max_length=30)),
                ('Nombre_subcircuito', models.CharField(max_length=30)),
                ('dependencia_Id', models.CharField(max_length=30)),
            ],
        ),
    ]
