# Generated by Django 5.0 on 2023-12-20 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0003_subcircuito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario_Policial_Id', models.CharField(max_length=40)),
                ('Asignacion_Rol_Id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionSubcircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignacion_Id', models.CharField(max_length=30)),
                ('Subcircuito_Id', models.CharField(max_length=30)),
                ('Usuario_Policial_Id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionVehiculoSubcircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignacion_Vehiculo_Id', models.CharField(max_length=20)),
                ('Vehiculo_Id', models.CharField(max_length=30)),
                ('Subcircuito_Id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mantenimiento_Id', models.CharField(max_length=20)),
                ('Fecha_Hora_Ingreso', models.CharField(max_length=20)),
                ('Kilometraje_Actual_Ingreso', models.CharField(max_length=20)),
                ('Tipo_Mantenimiento', models.CharField(max_length=20)),
                ('Vehiculo_Id', models.CharField(max_length=20)),
                ('Usuario_Policial_Id', models.CharField(max_length=20)),
                ('Subtotal', models.CharField(max_length=30)),
                ('Iva', models.CharField(max_length=30)),
                ('Total', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modulo_Id', models.CharField(max_length=40)),
                ('Nombre_Modulo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orden_Id', models.CharField(max_length=30)),
                ('Mantenimiento_Id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol_Id', models.CharField(max_length=40)),
                ('Nombre_Rol', models.CharField(max_length=40)),
                ('Descripcion_Rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solicitud_Id', models.CharField(max_length=20)),
                ('Fecha_Hora', models.CharField(max_length=20)),
                ('Kilometraje_Actual', models.CharField(max_length=20)),
                ('Vehiculo_Id', models.CharField(max_length=20)),
                ('Usuario_Policial_Id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehiculo_Id', models.CharField(max_length=40)),
                ('Tipo_Vehiculo', models.CharField(max_length=20)),
                ('Placa', models.CharField(max_length=20)),
                ('Chasis', models.CharField(max_length=20)),
                ('Marca', models.CharField(max_length=20)),
                ('Modelo', models.CharField(max_length=20)),
                ('Motor', models.CharField(max_length=20)),
                ('Kilometraje', models.IntegerField()),
                ('Cilindraje', models.IntegerField()),
                ('Capacidad_Carga', models.IntegerField()),
                ('Capacidad_Pasajeros', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='subcircuito',
            old_name='Subcircuito',
            new_name='Subcircuito_Id',
        ),
        migrations.RemoveField(
            model_name='usuariopolicial',
            name='dependencia_id',
        ),
        migrations.AddField(
            model_name='usuariopolicial',
            name='Usuario_Policial_Id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='OrdenCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=django.utils.timezone.now)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Tipo_Combustible', models.CharField(max_length=30)),
                ('Esta_Aprobado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policia1loja.vehiculo')),
            ],
        ),
    ]
