# Generated by Django 5.0 on 2024-01-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0004_asignacionrol_asignacionsubcircuito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopolicial',
            name='correo_electronico',
            field=models.CharField(default='no disponible', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopolicial',
            name='dependencia_Id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='policia1loja.dependencia'),
            preserve_default=False,
        ),
    ]
