# Generated by Django 5.0 on 2024-01-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0005_usuariopolicial_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopolicial',
            old_name='dependencia_Id',
            new_name='dependencia',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='dependencia_Id',
        ),
        migrations.RemoveField(
            model_name='usuariopolicial',
            name='Contraseña',
        ),
        migrations.RemoveField(
            model_name='usuariopolicial',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='usuariopolicial',
            name='Usuario_Policial_Id',
        ),
    ]
