# Generated by Django 5.0 on 2024-01-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0007_remove_subcircuito_subcircuito_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudmantenimiento',
            old_name='Solicitud_Id',
            new_name='Solicitud',
        ),
        migrations.RemoveField(
            model_name='asignacionsubcircuito',
            name='Asignacion_Id',
        ),
        migrations.RemoveField(
            model_name='asignacionsubcircuito',
            name='Subcircuito_Id',
        ),
        migrations.RemoveField(
            model_name='asignacionsubcircuito',
            name='Usuario_Policial_Id',
        ),
        migrations.RemoveField(
            model_name='asignacionvehiculosubcircuito',
            name='Asignacion_Vehiculo_Id',
        ),
        migrations.RemoveField(
            model_name='asignacionvehiculosubcircuito',
            name='Subcircuito_Id',
        ),
        migrations.RemoveField(
            model_name='asignacionvehiculosubcircuito',
            name='Vehiculo_Id',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Mantenimiento_Id',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Usuario_Policial_Id',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Vehiculo_Id',
        ),
        migrations.RemoveField(
            model_name='solicitudmantenimiento',
            name='Usuario_Policial_Id',
        ),
        migrations.RemoveField(
            model_name='solicitudmantenimiento',
            name='Vehiculo_Id',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Vehiculo_Id',
        ),
        migrations.AddField(
            model_name='asignacionsubcircuito',
            name='Subcircuito',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.subcircuito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacionsubcircuito',
            name='Usuario_Policial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.usuariopolicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacionvehiculosubcircuito',
            name='Subcircuito',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.subcircuito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacionvehiculosubcircuito',
            name='Vehiculo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.vehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='Usuario_Policial',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.usuariopolicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='Vehiculo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.vehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='Usuario_Policial',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.usuariopolicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='Vehiculo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='policia1loja.vehiculo'),
            preserve_default=False,
        ),
    ]
