# Generated by Django 5.0 on 2024-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0009_dependencia_codigo_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopolicial',
            name='identificacion',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
