# Generated by Django 5.0 on 2024-01-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0010_usuariopolicial_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopolicial',
            name='subcircuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policia1loja.subcircuito'),
        ),
    ]
