# Generated by Django 5.0 on 2024-01-18 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0011_usuariopolicial_subcircuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmantenimiento',
            name='Fecha_Hora',
        ),
        migrations.RemoveField(
            model_name='solicitudmantenimiento',
            name='Kilometraje_Actual',
        ),
        migrations.RemoveField(
            model_name='solicitudmantenimiento',
            name='Solicitud',
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='observaciones',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='kilometraje_actual',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
