# Generated by Django 5.0 on 2024-01-19 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0012_remove_solicitudmantenimiento_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Fecha_Hora_Ingreso',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Iva',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Kilometraje_Actual_Ingreso',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Subtotal',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Tipo_Mantenimiento',
        ),
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='Total',
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='imagen_parte_policial',
            field=models.ImageField(default=2, upload_to='partes_policiales/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='kilometraje_actual',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('M1', 'Mantenimiento 1'), ('M2', 'Mantenimiento 2'), ('M3', 'Mantenimiento 3')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
