# Generated by Django 5.0 on 2024-01-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia1loja', '0013_remove_mantenimientopreventivo_fecha_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
